name: Branch Detection Workflow

on:
  push:
    branches:
      - '*'
    tags:
      - '*'
  pull_request:
    branches:
      - '*'
  workflow_dispatch:

jobs:
  detect-branch:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    
    # Skip everything unless this is actually a v* tag
    if: startsWith(github.ref, 'refs/tags/v')

    steps:
      - name: Echo branch
        run: echo "${{ github.event.base_ref }}"